# Generated by Django 3.2 on 2023-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SlugField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], default='user', verbose_name='Роль'),
        ),
    ]
