# Generated by Django 3.2 on 2023-03-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SlugField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], verbose_name='Роль'),
        ),
    ]
