# Generated by Django 3.2 on 2023-03-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_alter_title_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
